# -*- mode: ruby -*-
# vi: set ft=ruby :

box_name = 'rocky-9.4-base'
hostname = 'rocky9-4-base'

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.box      = box_name
  config.vm.hostname = hostname

  config.vm.define hostname

  config.vm.disk :disk, size: "16GB", primary: true

  config.vm.provider 'vmware_desktop' do |vmware|
    vmware.gui = false
    vmware.vmx["ethernet0.virtualDev"] = "vmxnet3"
    vmware.vmx['memsize'] = 1024
    vmware.vmx['numvcpus'] = 1
    vmware.whitelist_verified = true
  end

  config.vm.synced_folder ENV['HOME'].to_s, '/host-data'
  config.ssh.insert_key = false
end
